const lang = {
  common: {
    zh: {
      liquid_providing: '流动性挖矿',
      trading_fee: '平台手续费',
      booster_apy: 'Booster 年化收益',
      mint_total_apy: '挖矿年化收益',
      borrow_total_ar: '借款利息年化',
      borrow_apy: '借款年利率',
      action_farm: '挖矿',
      action_manage: '管理',
      action_supply: '存款',
      action_withdraw: '取款',
      action_stake: '质押',
      action_deposit: '质押',
      action_stake_add: '增加质押',
      action_unstake: '解押',
      action_unstake_claimall: '解押&全部领取',
      action_claim: '领取收益',
      action_liquidate: '清算',
      action_approve: '授权',
      action_supplying: '正在存款 ',
      action_withdrawing: '正在取款 ',
      action_staking: '正在质押 ',
      action_staking_add: '正在增加质押 ',
      action_unstaking: '正在解押 ',
      action_unstaking_claimall: '正在解押&领取全部收益 ',
      action_claiming: '正在领取 ',
      action_claiming_all: '正在全部领取',
      action_claim_short: '领取',
      action_claim_all: '全部领取',
      action_approving: '正在授权 ',
      action_liquidating: '清算中',
      action_despositing: '正在质押 ',
      action_swap: '兑换',
      action_swaping: '正在兑换 ',
      action_lock: '锁仓',
      action_locking: '正在锁仓 ',
      action_lock_add: '增加锁仓',
      action_locking_add: '正在增加锁仓 ',
      action_lock_extend: '延长锁仓时间',
      action_lock_extending: '正在延长锁仓时间 ',
      action_enroll: '同步 ',
      action_enrolling: '正在同步 ',
      button_max: '全部',
      action: '操作',
      source: '来源',
      token: 'Token',
      loading: '加载中...',
      close: '关闭',
      balance: '钱包余额',
      desposit: '已质押',
      desposit_add: '增加质押',
      borrow: '借款',
      total: '综合',
      apy: '年化收益',
      fee: '手续费',
      entrance: '入场',
      refund: '复投',
      liquidity_farm: '流动性挖矿',
      lavarage_farm: '杠杆挖矿',
      farm: '挖矿',
      my_rewards: '我的收益',
      percent: '比例',
      current_position: '仓位',
      current_debt: '负债',
      you_will_recieve: '您大约可获得',
      settings: '设置',
      slippage: '交易滑点',
      save: '保存',
      borrow_token: '借款Token',
      borrow_source: '借款来源',
      infotip_refresh_and_retry: '请刷新页面后重试',
      infotip_title_info: '提示',
      infotip_title_error: '错误',
      infotip_title_success: '提示',
      infotip_success: '成功',
      infotip_fail: '失败',
      infotip_check_metamask: '请检查钱包是否已经解锁并可以正常连接',
      infotip_check_network: '请切换钱包连接网络到 {}',
      infotip_slippage:
        '开杠杆会产生0.3%的交易手续费及对应滑点成本，请谨慎选择杠杆倍数',
      infotip_unstake:
        '杠杆用户解押将会产生本金+借款部分的0.3% swap 手续费及对应滑点，请避免大资金解押',
      button_loading: '加载中',
      button_loading_more: '点击加载更多',
      warning: '警告',
      pools: '个矿池',
      positions: '个仓位',
      buy: '购买',
      add_liquidity: '添加流动性'
    },
    en: {
      liquid_providing: 'Liquid Providing',
      trading_fee: 'Platform Fee',
      mint_total_apy: 'Farm APY',
      borrow_total_ar: 'Borrow A-R',
      borrow_apy: 'Borrow APY',
      loading: 'Loading...',
      action_farm: 'FARM',
      action_manage: 'Manage',
      action_supply: 'Deposit',
      action_withdraw: 'Withdraw',
      action_stake: 'Stake',
      action_stake_add: 'Add Desposit',
      action_deposit: 'Desposit',
      action_unstake: 'Unstake',
      action_unstake_claimall: 'Unstake&Claim All',
      action_claim: 'Claim',
      action_liquidate: 'Liquidate',
      action_approve: 'Approve',
      action_supplying: 'Depositing ',
      action_withdrawing: 'Withdrawing ',
      action_staking: 'Staking ',
      action_staking_add: 'Add Staking',
      action_unstaking: 'Unstaking ',
      action_unstaking_claimall: 'Unstaking&Claiming All ',
      action_claiming: 'Claiming ',
      action_claiming_all: 'Claiming All ',
      action_claim_short: 'Claim',
      action_claim_all: 'Claim All',
      action_approving: 'Approving ',
      action_liquidating: 'Liquidating ',
      action_despositing: 'Despositing ',
      action_swap: 'Swap',
      action_swaping: 'Swaping ',
      action_lock: 'Lock',
      action_locking: 'Locking ',
      action_lock_add: 'Lock Add',
      action_locking_add: 'Locking Add ',
      action_lock_extend: 'Extend lock duration',
      action_lock_extending: 'Extending lock duration ',
      action_enroll: 'Enroll',
      action_enrolling: 'Enrolling ',
      button_max: 'MAX',
      action: 'Action',
      source: 'Source',
      token: 'Token',
      liquidity_farm: 'Liquid Farming',
      lavarage_farm: 'Lavarage Farming',
      farm: 'Farming',
      my_rewards: 'My Rewards',
      close: 'Close',
      balance: 'Balance',
      desposit: 'Desposit',
      desposit_add: 'Add Desposit',
      borrow: 'Borrow',
      total: 'Total',
      apy: 'APY',
      fee: 'Fee',
      entrance: 'Entrance',
      refund: 'Refund',
      percent: 'Percent',
      current_position: 'Current Position',
      current_debt: 'Current Debt',
      you_will_recieve: 'You will recieve estimated',
      settings: 'Settings',
      slippage: 'Slippage',
      save: 'Save',
      borrow_token: 'Borrow',
      borrow_source: 'Source',
      infotip_refresh_and_retry: 'please refresh page and retry',
      infotip_title_info: 'INFO',
      infotip_title_error: 'ERROR',
      infotip_title_success: 'SUCCESS',
      infotip_success: 'Successful',
      infotip_fail: 'Failed',
      infotip_check_metamask: 'Please ensure your wallet is connected and unlocked',
      infotip_check_network: 'Please switch your wallet network to {}',
      infotip_slippage:
        'When the margin token type is the same as the borrowing token type, 0.3% of transaction fee and corresponding slippage cost will be incurred. Please choose the borrowing token type carefully.',
      infotip_unstake:
        'Leveraged users to Unstake token will incur a 0.3% swap fee of the principal + borrowed part and corresponding slippage. Please avoid large capital unstake',
      button_loading: 'Loading',
      button_loading_more: 'Load more',
      warning: 'Warning',
      pools: ' Pools',
      positions: ' Positions',
      buy: 'Buy',
      add_liquidity: 'Add Liquidity'
    },
    ru: {
      liquid_providing: 'Ликвидный майнинг',
      trading_fee: 'торговые комиссии',
      booster_apy: 'Booster APY',
      mint_total_apy: 'добыча APY',
      borrow_total_ar: 'ЗАЕМКА A-R',
      borrow_apy: 'ЗАЙМАТЬ APY',
      action_farm: 'ферма',
      action_manage: 'управлять',
      action_supply: 'депозит',
      action_withdraw: 'Вывод',
      action_stake: 'Залог',
      action_deposit: 'Залог',
      action_stake_add: 'Увеличить залог',
      action_unstake: 'Релиз',
      action_unstake_claimall: 'Релиз&Заявить все',
      action_claim: 'Получить',
      action_liquidate: 'Ликвидация',
      action_approve: 'Авторизация',
      action_supplying: 'Депозит ',
      action_withdrawing: 'Снятие ',
      action_staking: 'Залог ',
      action_staking_add: 'Залог увеличивается ',
      action_unstaking: 'Выпущенный ',
      action_unstaking_claimall: 'Выпущенный&Получение всей выручки ',
      action_claiming: 'Получение ',
      action_claiming_all: 'Получение всего',
      action_claim_short: 'получить',
      action_claim_all: 'Заявить все',
      action_approving: 'Авторизация ',
      action_liquidating: 'В стадии ликвидации',
      action_despositing: 'Залог ',
      button_max: 'Все',
      action: 'Действие',
      source: 'Источник',
      token: 'Токен',
      loading: 'Загрузка...',
      close: 'неисправность',
      balance: 'Баланс кошелька',
      desposit: 'Залог',
      desposit_add: 'Увеличить залог',
      borrow: 'заем',
      total: 'Всесторонний',
      apy: 'APY',
      fee: 'Плата за обработку',
      entrance: 'Вход',
      refund: 'Реинвестировать',
      liquidity_farm: 'ликвидности ферма',
      lavarage_farm: 'использовать ферму',
      farm: 'ферма',
      my_rewards: 'Мой заработок',
      percent: 'пропорция',
      current_position: 'Должность',
      current_debt: 'Долг',
      you_will_recieve: 'Вы можете получить о ',
      settings: 'Настраивать',
      slippage: 'проскальзывание',
      save: 'спасти',
      borrow_token: 'заем Токен',
      borrow_source: 'заем источник',
      infotip_refresh_and_retry: 'Обновите страницу и попробуйте еще раз',
      infotip_title_info: 'ИНФОРМАЦИЯ',
      infotip_title_error: 'ОШИБКА',
      infotip_title_success: 'УСПЕХ',
      infotip_success: 'успех',
      infotip_fail: 'отказ',
      infotip_check_metamask:
        'Пожалуйста, проверьте, был ли кошелек разблокирован и может ли он нормально подключаться',
      infotip_check_network:
        'Пожалуйста, переключите кошелек, чтобы подключиться к сети {}',
      infotip_slippage:
        'За кредитное плечо взимается комиссия за транзакцию в размере 0,3% и соответствующую стоимость проскальзывания, пожалуйста, внимательно выбирайте коэффициент кредитного плеча.',
      infotip_unstake:
        'Разблокировка пользователей с кредитным плечом повлечет за собой комиссию за своп в размере 0,3% и соответствующее проскальзывание основной суммы + заемной части, пожалуйста, избегайте крупных необеспеченных средств.',
      button_loading: 'Загрузка',
      button_loading_more: 'Нажмите, чтобы загрузить больше',
      warning: 'предостережение',
      pools: ' Бассейны',
      positions: ' позиции',
      buy: 'Купить',
      add_liquidity: 'Добавить ликвидность'
    }
  },
  nav: {
    zh: {
      home: '首页',
      bridge: '跨链桥',
      bank: '存款',
      farm: '杠杆挖矿',
      my_investment: '我的投资',
      liquidation: '清算',
      boardroom: '董事会',
      audit: '审计',
      docs: '文档',
      connectwallet: '连接钱包'
    },
    en: {
      home: 'Home',
      bridge: 'Bridge',
      bank: 'Bank',
      farm: 'Leverage Farm',
      my_investment: 'My Investment',
      liquidation: 'Liquidation',
      boardroom: 'Boardroom',
      audit: 'Audit',
      docs: 'Docs',
      connectwallet: 'Wallet'
    },
    ru: {
      index: 'Дом',
      pools: 'Бассейны',
      leverage_pools: 'Использовать',
      reinvest_pools: 'Реинвестировать',
      your_positions: 'Мои инвестиции',
      liquidation: 'ликвидация',
      earn: 'Зарабатывать',
      logout: 'Выйти',
      launchapp: 'Запуск Dapp',
      commingsoon: 'Скоро будет...',
      connectwallet: 'Кошелек',
      dao: 'DAO'
    }
  },
  footer: {
    zh: {
      audit_agencies: '审计机构',
      partners: '合作伙伴'
    },
    en: {
      audit_agencies: 'Audit Agencies',
      partners: 'Partners'
    },
    ru: {
      audit_agencies: 'Аудиторские агентства',
      partners: 'Партнеры'
    }
  },
  home: {
    zh: {
      tvl: '总锁仓金额',
      earn: '存款池',
      pools: '杠杆池',
      supply: '去存款',
      farm: '去挖矿',
      earned: '奖励',
      action: '操作',
      more: '更多',
      infotip_fetch_pools_error: '获取数据列表失败，'
    },
    en: {
      tvl: 'Total Value Locked',
      earn: 'Earn Pools',
      pools: 'Leverage Pools',
      supply: 'Supply',
      farm: 'Farm',
      earned: 'Earned',
      action: 'Action',
      more: 'More',
      infotip_fetch_pools_error: 'Fetch data list failed,'
    }
  },
  earn: {
    zh: {
      tvl: '总存款金额',
      your_supply: '您的存款',
      lending_pool: '存款池',
      apy: '年化收益',
      total_supply: '总存款',
      utilization: '借贷比',
      my_supply: '我的存款',
      my_tvl: '我的锁仓',
      my_stake: '我的质押',
      my_rewards: '我的收益',
      tvl_short: '总锁仓',
      borrow_avaiable: '可用借款',
      infotip_fetch_pools_error: '获取存款池列表失败，',
      infotip_no_earn_pools: '暂无存款池'
    },
    en: {
      tvl: 'Total Desposit',
      your_supply: 'Your Deposit',
      lending_pool: 'Lending',
      apy: 'APY',
      total_supply: 'Total Supply',
      utilization: 'Utilization',
      my_supply: 'My Supply',
      my_tvl: 'My TVL',
      my_stake: 'My Stake',
      my_rewards: 'My Rewards',
      tvl_short: 'TVL',
      borrow_avaiable: 'Borrow Available',
      infotip_fetch_pools_error: 'Fetch supply pools list failed,',
      infotip_no_earn_pools: 'No Supply Pools'
    },
    ru: {
      tvl: 'TVL',
      your_supply: 'Ваш депозит',
      lending_pool: 'Кредитование',
      apy: 'APY',
      total_supply: 'Общее предложение',
      utilization: 'Утилизация',
      my_supply: 'Моя поставка',
      my_tvl: 'мой TVL',
      my_stake: 'Моя ставка',
      my_rewards: 'Мои награды',
      tvl_short: 'TVL',
      borrow_avaiable: 'Доступен заем',
      infotip_fetch_pools_error: 'Не удалось получить список пулов снабжения,',
      infotip_no_earn_pools: 'Нет пулов снабжения'
    }
  },
  pools: {
    zh: {
      pools: '矿池',
      farm_apy: '原始APY',
      tvl: '总锁仓金额',
      total_collateral: '总抵押金额',
      total_borrow: '总借款金额',
      active_positions: '总持仓',
      your_info: '您的信息',
      your_profit: '您的收益',
      your_total_collateral: '您的抵押',
      your_total_borrow: '您的借款',
      your_active_positions: '您的持仓',
      farm_pools: '杠杆挖矿',
      refund_pools: '复投挖矿',
      liquidity_pools: '流动性挖矿',
      lavarage: '杠杆倍数',
      my_stake: '我的质押',
      my_rewards: '我的收益',
      total_staked: '质押总额',
      apy: '年化收益',
      wallet_balance: '钱包余额',
      no_liquidity_pools: '暂无流动性挖矿矿池',
      no_leverage_pools: '暂无杠杆挖矿矿池',
      infotip_fetch_pools_error: '获取矿池列表失败，'
    },
    en: {
      pools: 'Pools',
      farm_apy: 'Farm APY',
      tvl: 'Total Value Locked',
      total_collateral: 'Total Collateral',
      total_borrow: 'Total Borrow',
      active_positions: 'Active Positions',
      your_info: 'Your Info',
      your_profit: 'Your Profit',
      your_total_collateral: 'Total Collateral',
      your_total_borrow: 'Total Borrow',
      your_active_positions: 'Your Positions',
      liquidity_pools: 'Liquidity',
      farm_pools: 'Leverage',
      refund_pools: 'Refund',
      lavarage: 'Leverage',
      my_stake: 'My Stake',
      my_rewards: 'My Rewards',
      total_staked: 'Total Staked',
      apy: 'APY',
      wallet_balance: 'Wallet Balance',
      no_liquidity_pools: 'No Liquidity Pools',
      no_leverage_pools: 'No Leverage Pools',
      infotip_fetch_pools_error: 'Fetch pool list failed,'
    },
    ru: {
      tvl: 'Общая стоимость заблокирована',
      total_collateral: 'Общая сумма залога',
      total_borrow: 'Всего заем',
      active_positions: 'Активные позиции',
      your_info: 'Ваша информация',
      your_profit: 'Ваша прибыль',
      your_total_collateral: 'Общая сумма залога',
      your_total_borrow: 'Всего заем',
      your_active_positions: 'Ваши позиции',
      liquidity_pools: 'Ликвидность',
      farm_pools: 'Использовать',
      refund_pools: 'Возврат',
      lavarage: 'Использовать',
      my_stake: 'Моя ставка',
      my_rewards: 'Мои награды',
      total_staked: 'Общая ставка',
      apy: 'APY',
      wallet_balance: 'Баланс Кошелька',
      no_liquidity_pools: 'Нет пулов ликвидности',
      no_leverage_pools: 'Пулы без кредитного плеча',
      infotip_fetch_pools_error: 'Не удалось получить список пула,'
    }
  },
  your_positions: {
    zh: {
      total_amount: '您的总投资',
      total_rewards: 'YEX 奖励',
      farm_pools: '杠杆挖矿',
      liquidity_pools: '流动性挖矿',
      earn_pools: '存款池',
      pool: '矿池',
      token: 'Token',
      apy: '年化收益',
      debt: '负债',
      my_debt: '我的负债',
      debt_ratio: '借贷比',
      liquidation_rate: '风险率',
      rewards: '收益',
      my_stake: '我的质押',
      my_rewards: '我的收益',
      opt: '操作',
      liquidation_factor: '清算系数',
      infotip_fetch_pools_error: '获取投资列表失败，'
    },
    en: {
      total_amount: 'Total Amount',
      total_rewards: 'YEX Rewards',
      liquidity_pools: 'Liquidity Pools',
      farm_pools: 'Leverage Pools',
      earn_pools: 'Lending Pools',
      pool: 'Pool',
      token: 'Token',
      apy: 'Apy',
      debt: 'Debt',
      my_debt: 'My Debt',
      debt_ratio: 'Debt Ratio',
      liquidation_rate: 'Risk Rate',
      rewards: 'Rewards',
      my_stake: 'My Stake',
      my_rewards: 'My Rewards',
      opt: 'Action',
      liquidation_factor: 'Liquidation Factor',
      infotip_fetch_pools_error: 'Fetch invest list failed,'
    },
    ru: {
      total_amount: 'Общая сумма',
      total_rewards: 'Booster Награды',
      liquidity_pools: 'Пулы ликвидности',
      farm_pools: 'Пулы кредитного плеча',
      earn_pools: 'Кредитные пулы',
      pool: 'Бассейн',
      token: 'Токен',
      apy: 'Apy',
      debt: 'Долг',
      my_debt: 'Мой долг\n',
      debt_ratio: 'Коэффициент задолженности',
      liquidation_rate: 'Уровень риска',
      rewards: 'Награды',
      my_stake: 'Моя ставка',
      my_rewards: 'Мои награды',
      opt: 'Действие',
      liquidation_factor: 'Фактор ликвидации',
      infotip_fetch_pools_error: 'Не удалось получить список инвестиций,'
    }
  },
  liquidation: {
    zh: {
      liquidation: '清算池',
      pool: '矿池',
      desposit: '质押额',
      borrow: '借款额',
      debt_radio: '借贷比',
      risk_rate: '风险率',
      action: '操作',
      liquidation_factor: '清算系数',
      infotip_fetch_pools_error: '获取清算池列表失败，'
    },
    en: {
      liquidation: 'Liquidation Pool',
      pool: 'Pool',
      desposit: 'Pledge',
      borrow: 'Loan',
      debt_radio: 'Loan ratio',
      risk_rate: 'Risk rate',
      action: 'Action',
      liquidation_factor: 'Liquidation Factor',
      infotip_fetch_pools_error: 'Fetch liquidation list failed,'
    },
    ru: {
      liquidation: 'Ликвидационный пул',
      pool: 'Бассейн',
      desposit: 'Залог',
      borrow: 'Заем',
      debt_radio: 'Коэффициент ссуды',
      risk_rate: 'Уровень риска',
      action: 'Действие',
      liquidation_factor: 'Фактор ликвидации',
      infotip_fetch_pools_error: 'Не удалось получить список ликвидации,'
    }
  },
  ido: {
    zh: {
      select_token: '选择Token',
      swap_limit: '可兑换额度',
      swap_feerate: '交易手续费',
      gas_fee: 'Gas手续费',
      swap_min: '最少兑换',
      slippage: '交易滑点',
      fund_raising_progress: '进度',
      amount_raised: '已完成',
      total_fund_raising: '总金额',
      total_deposit: '总质押',
      my_deposit: '我的质押',
      earned: '奖励',
      start_time: '挖矿开启时间',
      farm: '去挖矿',
      rule_description: 'YEE跨链桥功能说明',
      crosschain_swap: '跨链兑换',
      crosschain: '跨链',
      trade_confirmation: '交易确认',
      trade_processing: '交易进行中',
      trade_waiting: '交易待处理',
      trade_infomation: '交易明细',
      transfered: '已转出',
      idfox_transfer: '转出',
      stake_idfox: '去抵押iDFOX',
      estimated_swap: '预计可兑换'
    },
    en: {
      select_token: 'Select Token',
      swap_limit: 'Swap Limit Amount',
      swap_feerate: 'Swap Fee Rate',
      gas_fee: 'Gas Fee',
      swap_min: 'Swap Min Amount',
      slippage: 'Trade Slippage',
      fund_raising_progress: 'Fund Raising Progress',
      amount_raised: 'Amount Raised',
      total_fund_raising: 'Total Fund Raising',
      total_deposit: 'Total Deposit',
      my_deposit: 'My Deposit',
      earned: 'Earned',
      start_time: 'Farm Start Time',
      farm: 'Farm',
      rule_description: 'YEE Bridge Rule Description',
      crosschain_swap: 'Crosschain Swap',
      crosschain: 'CROSSCHAIN',
      trade_confirmation: 'Trade Confirmation',
      trade_processing: 'Trade Processing',
      trade_waiting: 'Trade Waiting',
      trade_infomation: 'Trade Infomation',
      transfered: 'Transfered',
      idfox_transfer: ' Transfer',
      stake_idfox: 'Stake iDFOX',
      estimated_swap: 'Estimated Swap Amount'
    }
  },
  boardroom: {
    zh: {
      current_price: '当前价格',
      block_rewards_rate: '出块奖励',
      block: '块',
      circulating_supply: '供应量',
      twap: '加权均价',
      th: '次',
      inflation_burn: '增发 - 通缩',
      next_epoch: '下一轮',
      inflation_amount: '增发数量',
      burn_amount: '通缩数量',
      boardroom_rewards_pool: '董事会奖励池',
      total_deposit: '总质押',
      my_deposit: '我的质押',
      earned: '奖励',
      deposit: '质押',
      withdraw: '解押',
      claim: '领取'
    },
    en: {
      current_price: 'Current Price',
      block_rewards_rate: 'Block Rewards',
      block: 'Block',
      circulating_supply: 'Circulating Supply',
      twap: 'TWAP',
      th: 'TH',
      inflation_burn: 'INFLATION - BURN',
      next_epoch: 'Next Epoch',
      inflation_amount: 'Inflation Amount',
      burn_amount: 'Burn Amount',
      boardroom_rewards_pool: 'Boardroom Rewards Pool',
      total_deposit: 'Total Deposit',
      my_deposit: 'My Deposit',
      earned: 'Earned',
      deposit: 'Deposit',
      withdraw: 'Withdraw',
      claim: 'Claim'
    }
  },
  dao: {
    zh: {
      Lottery: '彩票',
      Lockup: '锁仓',
      Lockuping: '正在锁仓 ',
      unlockApply: '申请解锁',
      unlockApplying: '正在申请解锁 ',
      unstake: '解锁',
      unstaking: '正在解锁 ',
      Round: '轮次',
      TokenID: '令牌ID',
      Yournumbers: '你的号码',
      Prizes: '奖励',
      success: '成功',
      failed: '失败',
      searchplace: '请选择您的号码',
      Winningnumbers: '中奖号码',
      Totalprizes: '总奖金',
      Nomatched: '不匹配',
      Winners: '中奖者',
      Prizepot: '奖池',
      Burned: '销毁',
      tickerText: '查看您的票',
      History: '历史',
      Dividend: '红利',
      lockPos: '锁仓金额',
      unlockPos: '可提取金额',
      lockPosAll: '总锁仓金额',
      lockPeriod: '锁仓周期',
      APY: '年化收益',
      Awardamount: '奖励金额',
      Authorize: '授权',
      myLock: '我的锁仓',
      week: '周',
      PoolSize: '奖池总量',
      infotip_fetch_pools_error: '获取DAO列表失败，'
    },
    en: {
      Lottery: 'Lottery',
      Lockup: 'Lock Up',
      Lockuping: 'Locking up ',
      unlockApply: 'Apply unlock',
      unlockApplying: 'Apply unlocking ',
      unstake: 'Unlock',
      unstaking: 'Unlocking ',
      Round: 'Round',
      TokenID: 'Token ID',
      Yournumbers: 'Your numbers',
      Prizes: 'Prizes',
      success: 'Win',
      failed: 'Failure',
      searchplace: 'Select lottery number',
      Winningnumbers: 'Winning numbers',
      Totalprizes: 'Total Prizes',
      Nomatched: 'No.Matched',
      Winners: 'Winners',
      Prizepot: 'Prize pot',
      Burned: 'Burned',
      tickerText: 'View your tickets',
      History: 'History',
      Dividend: 'Dividend',
      lockPos: 'Locked Amount',
      unlockPos: 'Unlocked Amount',
      lockPosAll: 'Total Locked Position',
      lockPeriod: 'Locked Period',
      APY: 'APY',
      Awardamount: 'Award Amount',
      Authorize: 'Approve',
      myLock: 'My Lock-ups',
      week: 'week',
      PoolSize: 'PoolSize',
      infotip_fetch_pools_error: 'Fetch DAO pools list failed,'
    },
    ru: {
      Lottery: 'Лотерея',
      Lockup: 'Запереть',
      Lockuping: 'Закрываться ',
      unlockApply: 'Применить разблокировку',
      unlockApplying: 'Применить разблокировку ',
      unstake: 'Разблокировать',
      unstaking: 'Разблокировка ',
      Round: 'Круглый',
      TokenID: 'Идентификатор токена',
      Yournumbers: 'Ваши числа',
      Prizes: 'Призы',
      success: 'Выиграть',
      failed: 'Отказ',
      searchplace: 'Выберите номер лотереи',
      Winningnumbers: 'Выигрышные числа',
      Totalprizes: 'Выигрышные числа',
      Nomatched: 'Нет совпадений',
      Winners: 'Победители',
      Prizepot: 'Призовой фонд',
      Burned: 'Сгорел',
      tickerText: 'Посмотреть свои билеты',
      History: 'История',
      Dividend: 'Дивиденды',
      lockPos: 'Заблокированная сумма',
      unlockPos: 'Разблокированная сумма',
      lockPosAll: 'Общая заблокированная позиция',
      lockPeriod: 'Закрытый период',
      APY: 'APY',
      Awardamount: 'Сумма вознаграждения',
      Authorize: 'Авторизация',
      myLock: 'Мои блокировки',
      week: 'неделя',
      PoolSize: 'Размер бассейна',
      infotip_fetch_pools_error: 'Не удалось получить список пулов DAO,'
    }
  }
}

export default lang
